---
name: backup
services:
  kopia:
    image: kopia/kopia:latest
    container_name: kopia
    hostname: kopia-docker
    user: "1000"
    restart: unless-stopped
    command:
      - server
      - start
      - --disable-csrf-token-checks
      - --insecure
      - --address=0.0.0.0:51515
      - --server-username=${USERNAME}
      - --server-password=${SECRET_PASSWORD}
    ports:
      - ${VARIABLE_BIND_ADDRESS}:51515:51515
    volumes:
      - $HOME/homelab-data/kopia/config:/app/config
      - kopia-cache:/app/cache
      - $HOME/homelab-data/kopia/logs:/app/logs
      - $HOME/homelab-data:/data:ro
      - $HOME/homelab-data/kopia/tmp:/tmp:shared

volumes:
  kopia-cache:
    name: kopia-cache

networks:
  default:
    name: backup
