---
name: rybbit
services:
  clickhouse:
    image: clickhouse/clickhouse-server:25.4.2
    container_name: rybbit_clickhouse
    user: "462"
    restart: unless-stopped
    environment:
      - CLICKHOUSE_PASSWORD=${CLICKHOUSE_PASSWORD}
      - CLICKHOUSE_USER=default
      - CLICKHOUSE_DB=${CLICKHOUSE_DB}
    volumes:
      - $HOME/homelab-data/rybbit/clickhouse:/var/lib/clickhouse
      - ./clickhouse_config:/etc/clickhouse-server/config.d
    healthcheck:
      test:
        [
          CMD,
          wget,
          --no-verbose,
          --tries=1,
          --spider,
          "http://localhost:8123/ping",
        ]
      interval: 3s
      timeout: 5s
      retries: 5
      start_period: 10s

  postgres:
    image: postgres:17.4
    container_name: rybbit_postgres
    user: "462"
    restart: unless-stopped
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - $HOME/homelab-data/rybbit/db:/var/lib/postgresql/data
    healthcheck:
      # yamllint disable-line rule:quoted-strings
      test: [CMD-SHELL, "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 3s
      timeout: 5s
      retries: 5
      start_period: 10s

  backend:
    image: ghcr.io/rybbit-io/rybbit-backend:latest
    container_name: rybbit_backend
    user: "462"
    restart: unless-stopped
    ports:
      - ${HOST_BACKEND_PORT}:3001
    environment:
      - NODE_ENV=production
      - CLICKHOUSE_HOST=http://clickhouse:8123
      - CLICKHOUSE_DB=${CLICKHOUSE_DB}
      - CLICKHOUSE_PASSWORD=${CLICKHOUSE_PASSWORD}
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - BETTER_AUTH_SECRET=${BETTER_AUTH_SECRET}
      - BASE_URL=${BASE_URL}
      - DISABLE_SIGNUP=${DISABLE_SIGNUP}
    healthcheck:
      test:
        [
          CMD,
          wget,
          --no-verbose,
          --tries=1,
          --spider,
          "http://127.0.0.1:3001/api/health",
        ]
      interval: 3s
      timeout: 5s
      retries: 5
      start_period: 10s
    depends_on:
      clickhouse:
        condition: service_healthy
      postgres:
        condition: service_started

  client:
    image: ghcr.io/rybbit-io/rybbit-client:latest
    container_name: rybbit_client
    user: "462"
    restart: unless-stopped
    ports:
      - ${HOST_CLIENT_PORT}:3002
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_BACKEND_URL=${BASE_URL}
      - NEXT_PUBLIC_DISABLE_SIGNUP=${DISABLE_SIGNUP}
    depends_on:
      - backend
