---
server:
  port: 80
  baseURL: /
  logging:
    - levels: info|warning|error
  sources:
    - path: /srv
      config:
        defaultEnabled: true
userDefaults:
  preview:
    image: true
    popup: true
    video: false
    office: false
    highQuality: false
  darkMode: true
  disableSettings: false
  singleClick: false
  permissions:
    admin: false
    modify: false
    share: false
    api: false
auth:
  methods:
    proxy:
      enabled: true
      header: Remote-User
    password:
      enabled: false
