---
name: bunkerweb
services:
  bunkerweb:
    image: bunkerity/bunkerweb-all-in-one:1.6.2
    container_name: bunkerweb
    user: "422"
    restart: unless-stopped
    ports:
      - 80:8080/tcp
      - 443:8443/tcp
      - 443:8443/udp
    env_file: .env
    volumes:
      - $HOME/homelab-data/bunkerweb/data:/data

networks:
  default:
    name: bunkerweb
