services:
  pocket-id:
    image: ghcr.io/pocket-id/pocket-id:v1
    container_name: pocket-id
    user: 420:920
    restart: unless-stopped
    env_file: .env
    ports:
      - 127.0.0.1:1411:1411
      - 100.110.247.44:14111:1411
    volumes:
      - $HOME/homelab-data/pocket-id:/app/data
    healthcheck:
      test: [ "CMD", "/app/pocket-id", "healthcheck" ]
      interval: 1m30s
      timeout: 5s
      retries: 2
      start_period: 10s
