---
name: pocket-id
services:
  pocket-id:
    image: ghcr.io/pocket-id/pocket-id:v1
    container_name: pocket-id
    user: 420:920
    restart: unless-stopped
    ports:
      - 1411:1411
    env_file: .env
    volumes:
      - $HOME/homelab-data/pocket-id:/app/data
    healthcheck:
      test: [ "CMD", "/app/pocket-id", "healthcheck" ]
      interval: 1m30s
      timeout: 5s
      retries: 2
      start_period: 10s
