---
repos:
  - repo: local
    hooks:
      - id: sops-encrypt
        name: Encrypt secrets with sops
        entry: ./sops-encrypt.sh
        language: script
        verbose: true
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-shebang-scripts-are-executable
      - id: check-yaml
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: trailing-whitespace
  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.24.2
    hooks:
      - id: gitleaks
