---
creation_rules:
  - age: >-
      age13lquc0sm0nyclv6c473f7npw695tsp48yeh4zdg0js55jgej5a7qaydh4s,
      age1hqx4rxzpl04cwrxa2fxk2yk35h8jcqr6dq8ny2pen8vy4xjp6sjq5klft7,
      age1wg8qzaknhycvzuf98rhjjl33ahrcfpngqw7zzthjwll9yxqge97qkvh585,
      age1zswddtxr4gg0vgflk3jw2ah79syrfed7ru8jzh8p9x0srynv5drqucmr8q
