---
name: paperless
services:
  broker:
    image: docker.io/library/redis:7
    container_name: paperless-redis
    user: 430:930
    restart: unless-stopped
    volumes:
      - redisdata:/data

  db:
    image: docker.io/library/postgres:16
    container_name: paperless-db
    user: 430:930
    restart: unless-stopped
    environment:
      POSTGRES_DB: paperless
      POSTGRES_USER: paperless
      POSTGRES_PASSWORD: ${PAPERLESS_DB_PASSWORD}
    volumes:
      - $HOME/homelab-data/paperless/db:/var/lib/postgresql/data

  webserver:
    image: ghcr.io/paperless-ngx/paperless-ngx:latest
    container_name: paperless
    restart: unless-stopped
    ports:
      - "127.0.0.1:12000:8000"
    environment:
      - PAPERLESS_REDIS=redis://broker:6379
      - PAPERLESS_DBHOST=db
      - PAPERLESS_DBPASS=${PAPERLESS_DB_PASSWORD}
      - PAPERLESS_TIKA_ENABLED=1
      - PAPERLESS_TIKA_GOTENBERG_ENDPOINT=http://gotenberg:3000
      - PAPERLESS_TIKA_ENDPOINT=http://tika:9998
      - PAPERLESS_SECRET_KEY=${PAPERLESS_SECRET_KEY}
      - PAPERLESS_TIMEZONE=America/New_York
      - USERMAP_UID=430
      - USERMAP_GID=930
      - PAPERLESS_OCR_LANGUAGE=eng
      - PAPERLESS_FILENAME_FORMAT={{created_year}}/{{created_month}}/{{correspondent}}/{{title}}
      - PAPERLESS_CONSUMER_DISABLE=true
      - PAPERLESS_EMAIL_PARSE_DEFAULT_LAYOUT=2
    volumes:
      - ${DATA_DIRECTORY}/data:/usr/src/paperless/data
      - ${DATA_DIRECTORY}/media:/usr/src/paperless/media
      - ${DATA_DIRECTORY}/export:/usr/src/paperless/export
    depends_on:
      - db
      - broker
      - gotenberg
      - tika

  gotenberg:
    image: docker.io/gotenberg/gotenberg:8.7
    container_name: gotenberg
    command:
      - "gotenberg"
      - "--chromium-disable-javascript=true"
      - "--chromium-allow-list=file:///tmp/.*"
    restart: unless-stopped
    user: 430:930

  tika:
    image: docker.io/apache/tika:latest
    container_name: tika
    user: 430:930
    restart: unless-stopped

  protonmail-bridge:
    image: shenxn/protonmail-bridge
    container_name: protonmail-bridge
    restart: unless-stopped
    volumes:
      - protonmail:/root

volumes:
  redisdata:
    name: paperless-redisdata
    external: true
  protonmail:
    name: paperless-protonmail
    external: true
