name: syncthing
services:
  syncthing:
    image: lscr.io/linuxserver/syncthing:latest
    container_name: syncthing
    hostname: syncthing-nuc
    environment:
      - PUID=1002
      - PGID=1006
      - TZ=America/New_York
    volumes:
      - $HOME/homelab-data/syncthing/:/config
      - ${DATA_DIRECTORY}/remote-data/:/data
    env_file: .env
    ports:
      - 127.0.0.1:8384:8384
      - 22000:22000/tcp
      - 22000:22000/udp
      - 21027:21027/udp
    restart: unless-stopped
  filebrowser:
    image: gtstef/filebrowser
    container_name: filebrowser
    env_file: .env
    environment:
      FILEBROWSER_CONFIG: data/config.yaml
      FILEBROWSER_ADMIN_PASSWORD: admin
      TZ: America/New_York
    volumes:
      - ${DATA_DIRECTORY}/remote-data:/srv
      - ./config:/home/filebrowser/data
      - ./tmp/:/home/filebrowser/tmp/
    ports:
      - 18000:80
    restart: unless-stopped
