name: obsidian-sync
services:
  couchdb:
    image: couchdb
    container_name: couchdb-for-ols
    restart: always
    env_file: .env
    volumes:
      - ${DATA_DIRECTORY}/obsidian:/opt/couchdb/data
      - $HOME/homelab-data/obsidian-sync:/opt/couchdb/etc/local.d
    ports:
      - 127.0.0.1:5984:5984
