name: monitoring
services:
  dozzle:
    image: amir20/dozzle:latest
    container_name: dozzle
    restart: always
    env_file: .env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 8088:8080
  diun:
    image: crazymax/diun:latest
    command: serve
    container_name: diun
    env_file: .env
    environment:
      - TZ=America/New_York
      - DIUN_WATCH_WORKERS=10
      - DIUN_WATCH_SCHEDULE=0 */6 * * *
      - DIUN_WATCH_JITTER=30s
      - DIUN_PROVIDERS_DOCKER=true
      - DIUN_PROVIDERS_DOCKER_WATCHBYDEFAULT=true
      - DIUN_NOTIF_PUSHOVER_TOKEN=${PUSHOVER_TOKEN}
      - DIUN_NOTIF_PUSHOVER_RECIPIENT=${PUSHOVER_CLIENT_ID}
      - DIUN_NOTIF_PUSHOVER_TEMPLATETITLE='{{ .Meta.Name }} {{ if (eq .Entry.Status "new") }}is available{{ else }}has been updated{{ end }}'
    volumes:
      - diun_data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always
volumes:
  netdatalib:
  netdatacache:
  diun_data:
