---
name: pangolin
services:
  pangolin:
    image: fosrl/pangolin:1.6.2
    container_name: pangolin
    restart: unless-stopped
    volumes:
      - $HOME/homelab-data/pangolin:/app/config
    healthcheck:
      test: [CMD, curl, -f, "http://localhost:3001/api/v1/"]
      interval: 10s
      timeout: 10s
      retries: 15

  gerbil:
    image: fosrl/gerbil:1.0.0
    container_name: gerbil
    restart: unless-stopped
    depends_on:
      pangolin:
        condition: service_healthy
    command:
      - --reachableAt=http://gerbil:3003
      - --generateAndSaveKeyTo=/var/config/key
      - --remoteConfig=http://pangolin:3001/api/v1/gerbil/get-config
      - --reportBandwidthTo=http://pangolin:3001/api/v1/gerbil/receive-bandwidth
    volumes:
      - $HOME/homelab-data/pangolin:/var/config
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    ports:
      - 51820:51820/udp
      - 4443:443
      - 8000:80
    extra_hosts:
      - host.docker.internal:host-gateway
  traefik:
    image: traefik:v3.4.1
    container_name: traefik
    restart: unless-stopped
    env_file: .env
    network_mode: service:gerbil

    depends_on:
      pangolin:
        condition: service_healthy
    command:
      - --configFile=/etc/traefik/traefik_config.yml
    volumes:
      - $HOME/homelab-data/pangolin/traefik:/etc/traefik:ro
      - $HOME/homelab-data/pangolin/letsencrypt:/letsencrypt
      - .$HOME/homelab-data/pangolin/logs:/var/log/traefik

networks:
  default:
    driver: bridge
    name: pangolin
