---
name: miniflux
services:
  miniflux:
    image: miniflux/miniflux:latest
    container_name: miniflux
    user: 450:950
    ports:
      - "9999:8080"
    env_file: .env
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:17-alpine
    container_name: miniflux_db
    user: 450:950
    environment:
      - POSTGRES_USER=miniflux
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=miniflux
    volumes:
      - $HOME/homelab-data/miniflux:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "miniflux"]
      interval: 10s
      start_period: 30s
