---
name: coral
services:
  coral:
    image: coralproject/talk:7
    container_name: coral
    restart: always
    ports:
      - 127.0.0.1:5000:5000
    depends_on:
      - mongo
      - redis
    environment:
      - MONGODB_URI=mongodb://mongo:27017/coral
      - REDIS_URI=redis://redis:6379
      - SIGNING_SECRET=${SIGNING_SECRET}
  mongo:
    image: mongo:4.2
    container_name: coral-redis
    volumes:
      - $HOME/homelab-data/coral/db:/data/db
  redis:
    image: redis:3.2
    container_name: coral-redis
    volumes:
      - coral-redis:/data

volumes:
  coral-redis:
