name: linkace
services:
  app:
    image: docker.io/linkace/linkace:latest
    user: "452"
    container_name: linkace
    restart: unless-stopped
    depends_on:
      - db
    ports:
      - "127.0.0.1:9669:80"
      - "100.110.247.44:9668:80"
    volumes:
      - ./.env:/app/.env
      - $HOME/homelab-data/linkace/backups:/app/storage/app/backups

  db:
    image: docker.io/library/mariadb:11.5
    container_name: linkace_db
    user: "452"
    restart: unless-stopped
    command: mariadbd --character-set-server=utf8mb4 --collation-server=utf8mb4_bin
    env_file: .env
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_DATABASE}
    volumes:
      - $HOME/homelab-data/linkace/db:/var/lib/mysql

  redis:
    container_name: linkace_redis
    user: "452"
    image: docker.io/bitnami/redis:7.4
    restart: unless-stopped
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
