---
name: monitoring
services:
  dozzle:
    image: amir20/dozzle:latest
    container_name: dozzle
    user: 412:910
    restart: always
    ports:
      - 8088:8080
    env_file: .env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
  diun:
    image: crazymax/diun:latest
    container_name: diun
    user: 413:910
    restart: always
    command: serve
    env_file: .env
    environment:
      - TZ=America/New_York
      - DIUN_WATCH_WORKERS=10
      - DIUN_WATCH_SCHEDULE=0 */6 * * *
      - DIUN_WATCH_JITTER=30s
      - DIUN_PROVIDERS_DOCKER=true
      - DIUN_PROVIDERS_DOCKER_WATCHBYDEFAULT=true
      - DIUN_NOTIF_PUSHOVER_TOKEN=${PUSHOVER_TOKEN}
      - DIUN_NOTIF_PUSHOVER_RECIPIENT=${PUSHOVER_CLIENT_ID}
    volumes:
      - diun_data:/data
      - /var/run/docker.sock:/var/run/docker.sock
volumes:
  diun_data:
