---
name: paperless
services:
  broker:
    image: docker.io/library/redis:7
    container_name: paperless-redis
    user: 430:930
    restart: unless-stopped
    volumes:
      - redisdata:/data

  db:
    image: docker.io/library/postgres:16
    container_name: paperless-db
    user: 430:930
    restart: unless-stopped
    environment:
      POSTGRES_DB: paperless
      POSTGRES_USER: paperless
      POSTGRES_PASSWORD: paperless
    volumes:
      - $HOME/homelab-data/paperless/db:/var/lib/postgresql/data

  webserver:
    image: ghcr.io/paperless-ngx/paperless-ngx:latest
    container_name: paperless
    user: 430:930
    restart: unless-stopped
    ports:
      - "127.0.0.1:12000:8000"
      - "100.110.247.44:12001:8000"
    env_file: .env
    environment:
      PAPERLESS_REDIS: redis://broker:6379
      PAPERLESS_DBHOST: db
      PAPERLESS_TIKA_ENABLED: 1
      PAPERLESS_TIKA_GOTENBERG_ENDPOINT: http://gotenberg:3000
      PAPERLESS_TIKA_ENDPOINT: http://tika:9998
    volumes:
      - ${DATA_DIRECTORY}/paperlessv2/data:/usr/src/paperless/data
      - ${DATA_DIRECTORY}/paperlessv2/media:/usr/src/paperless/media
      - ${DATA_DIRECTORY}/paperlessv2/export:/usr/src/paperless/export
    depends_on:
      - db
      - broker
      - gotenberg
      - tika

  gotenberg:
    image: docker.io/gotenberg/gotenberg:8.7
    container_name: gotenberg
    user: 430:930
    restart: unless-stopped
    command:
      - "gotenberg"
      - "--chromium-disable-javascript=true"
      - "--chromium-allow-list=file:///tmp/.*"

  tika:
    image: docker.io/apache/tika:latest
    container_name: tika
    user: 430:930
    restart: unless-stopped

  protonmail-bridge:
    image: shenxn/protonmail-bridge
    container_name: protonmail-bridge
    user: 430:930
    restart: unless-stopped
    volumes:
      - protonmail:/root

volumes:
  redisdata:
    name: paperless-redisdata
    external: true
  protonmail:
    name: paperless-protonmail
    external: true
