---
name: syncing
services:
  couchdb:
    image: couchdb:3.4.2
    container_name: couchdb-for-ols
    user: 1000:930
    restart: always
    ports:
      - 127.0.0.1:5984:5984
    environment:
      - COUCHDB_USER=${COUCHDB_USER}
      - COUCHDB_PASSWORD=${COUCHDB_PASSWORD}
    volumes:
      - /mnt/ssd/obsidian:/opt/couchdb/data
      - $HOME/homelab-data/obsidian/config:/opt/couchdb/etc/local.d
    profiles:
      - nuc

  syncthing:
    image: lscr.io/linuxserver/syncthing:latest
    container_name: syncthing
    hostname: syncthing-nuc
    restart: unless-stopped
    ports:
      - 127.0.0.1:8384:8384
      - 22000:22000/tcp
      - 22000:22000/udp
      - 21027:21027/udp
    environment:
      - PUID=432
      - PGID=930
      - TZ=America/New_York
    volumes:
      - $HOME/homelab-data/syncthing/:/config
      - /mnt/ssd/remote-data/:/data
    profiles:
      - nuc

  filebrowser:
    image: gtstef/filebrowser
    container_name: filebrowser
    user: 432:930
    restart: unless-stopped
    ports:
      - 127.0.0.1:18000:80
    environment:
      FILEBROWSER_CONFIG: data/config.yaml
      TZ: America/New_York
    volumes:
      - /mnt/ssd/remote-data:/srv
      - ./config:/home/filebrowser/data
      - ./tmp/:/home/filebrowser/tmp/
    profiles:
      - nuc

networks:
  default:
    name: syncing
