name: ytdl-sub
services:
  ytdl-sub:
    image: ghcr.io/jmbannon/ytdl-sub:latest
    container_name: ytdl-sub
    env_file: ../.env
    environment:
      - PUID=1000
      - PGID=13000
      - TZ=America/New_York
      - DOCKER_MODS=linuxserver/mods:universal-cron
      - CRON_SCHEDULE="0 */6 * * *"
      - CRON_RUN_ON_START=true
    volumes:
      - ./config:/config
      - ${DATA_DIRECTORY}/media:/data
    restart: unless-stopped
