---
name: searx
services:
  valkey:
    image: docker.io/valkey/valkey:8-alpine
    container_name: valkey
    user: 460:960
    restart: unless-stopped
    command: valkey-server --save 30 1 --loglevel warning
    volumes:
      - valkey-data:/data
    cap_drop:
      - ALL
    cap_add:
      - SETGID
      - SETUID
      - DAC_OVERRIDE
  searxng:
    image: docker.io/searxng/searxng:latest
    container_name: searxng
    user: 460:960
    restart: unless-stopped
    ports:
      - "7777:8080"
    environment:
      - SEARXNG_SECRET=${SEARXNG_SECRET}
      - SEARXNG_BASE_URL=https://searx.beanscloud.me/
      - UWSGI_WORKERS=4
      - UWSGI_THREADS=4
    volumes:
      - ./searxng:/etc/searxng:rw
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETGID
      - SETUID

volumes:
  valkey-data:
    name: sx-valkey-data
    external: true
