---
name: backup
services:
  kopia:
    image: kopia/kopia:latest
    user: "1000"
    container_name: kopia
    hostname: kopia-docker
    restart: unless-stopped
    ports:
      - 51515:51515
    command:
      - server
      - start
      - --disable-csrf-token-checks
      - --insecure
      - --address=0.0.0.0:51515
      - --server-username=${USERNAME}
      - --server-password=${SECRET_PASSWORD}
    env_file: .env
    volumes:
      - $HOME/homelab-data/kopia/config:/app/config
      - kopia-cache:/app/cache
      - $HOME/homelab-data/kopia/logs:/app/logs
      - $HOME/homelab-data:/data:ro
      - $HOME/homelab-data/kopia/tmp:/tmp:shared

volumes:
  kopia-cache:
