---
name: firefly
services:
  app:
    image: fireflyiii/core:latest
    container_name: firefly_iii_core
    hostname: app
    restart: always
    ports:
      - 127.0.0.1:8090:8080
    env_file: .env
    volumes:
      - $HOME/homelab-data/firefly-iii/upload:/var/www/html/storage/upload
    depends_on:
      - db

  db:
    image: mariadb:lts
    container_name: firefly_iii_db
    hostname: db
    user: 437:930
    restart: always
    environment:
      - MYSQL_DATABASE=firefly-iii
      - MYSQL_USER=firefly
      - MYSQL_PASSWORD=${FIREFLY_III_DB_PASSWORD}
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
    volumes:
      - $HOME/homelab-data/firefly-iii/db:/var/lib/mysql

  importer:
    image: fireflyiii/data-importer:latest
    container_name: firefly_iii_importer
    hostname: importer
    restart: always
    environment:
      - FIREFLY_III_URL=http://app:8080
      - VANITY_URL=${IMPORTER_VANITY_URL}
      - FIREFLY_III_ACCESS_TOKEN=${IMPORTER_ACCESS_TOKEN}
      - VERIFY_TLS_SECURITY=true
      - TRUSTED_PROXIES=**
      - TZ=America/New_York
    ports:
      - "127.0.0.1:8091:8080"
    env_file: .importer.env
    depends_on:
      - app

  cron:
    image: alpine
    container_name: firefly_iii_cron
    restart: always
    command: sh -c "echo \"*/30 * * * * wget -qO- http://app:8080/api/v1/cron/ELwfiGGVdCdQJsDV2X2sCQGXuTwPJuhq;echo\" | crontab - && crond -f -L /dev/stdout"

  firefly-pico:
    image: cioraneanu/firefly-pico:latest
    container_name: firefly-pico
    restart: unless-stopped
    ports:
      - 127.0.0.1:6972:80
    environment:
      - FIREFLY_URL=http://app:8080
      - DB_CONNECTION=pgsql
      - DB_HOST=firefly-pico-db
      - DB_PORT=5432
      - DB_DATABASE=firefly_pico
      - DB_USERNAME=firefly_pico
      - DB_PASSWORD=${PICO_POSTGRES_PASSWORD}
      - TZ=America/New_York
    depends_on:
      - app
      - firefly-pico-db

  firefly-pico-db:
    image: postgres:latest
    container_name: firefly_pico_db
    user: 438:930
    restart: unless-stopped
    environment:
      - POSTGRES_USER=firefly_pico
      - POSTGRES_PASSWORD=${PICO_POSTGRES_PASSWORD}
      - POSTGRES_DB=firefly_pico
    volumes:
      - $HOME/homelab-data/firefly-pico/db:/var/lib/postgresql/data

networks:
  default:
    name: firefly-iii
