---
name: memos
services:
  memos:
    image: neosmemo/memos:stable
    container_name: memos
    user: 434:930
    ports:
      - 5230:5230
    volumes:
      - $HOME/homelab-data/memos:/var/opt/memos
