---
name: beszel
services:
  beszel:
    image: henrygd/beszel:latest
    container_name: beszel
    user: 410:910
    restart: unless-stopped
    ports:
      - 8090:8090
    volumes:
      - $HOME/homelab-data/beszel/beszel_data:/beszel_data
      - $HOME/homelab-data/beszel/beszel_socket:/beszel_socket
