name: uptime-kuma
services:
  uptime-kuma:
    image: louislam/uptime-kuma:1
    container_name: uptime-kuma
    user: 414:910
    restart: unless-stopped
    ports:
      - 3001:3001
    volumes:
      - $HOME/homelab-data/uptime-kuma:/data
