---
name: uptime-kuma
services:
  uptime-kuma:
    image: louislam/uptime-kuma:1
    container_name: uptime-kuma
    restart: unless-stopped
    environment:
      - PUID=414
      - PGID=996
    ports:
      - 3001:3001
    volumes:
      - $HOME/homelab-data/uptime-kuma:/data
