---
# Usage:
#     mkdir -p ~/archivebox/data && cd ~/archivebox
#     curl -fsSL 'https://docker-compose.archivebox.io' > docker-compose.yml
#     docker compose run archivebox version
#     docker compose run archivebox config --set SAVE_ARCHIVE_DOT_ORG=False
#     docker compose run archivebox add --depth=1 'https://news.ycombinator.com'
#     docker compose run -T archivebox add < bookmarks.txt
#     docker compose up -d && open 'https://localhost:8000'
#     docker compose run archivebox help
# Documentation:
#     https://github.com/ArchiveBox/ArchiveBox/wiki/Docker#docker-compose
name: archivebox
services:
  archivebox:
    image: archivebox/archivebox:latest
    container_name: archivebox
    user: 435:930
    restart: unless-stopped
    ports:
      - 8070:8000
    env_file: .env
    volumes:
      - $HOME/homelab-data/archivebox/data:/data
    networks:
      - dns
    dns:
      - 172.20.0.53

  archivebox_scheduler:
    image: archivebox/archivebox:latest
    container_name: ab-scheduler
    user: 435:930
    restart: unless-stopped
    command: schedule --foreground --update --every=day
    env_file: .env
    volumes:
      - $HOME/homelab-data/archivebox/data:/data
    cpus: 1
    mem_limit: 2048m

  sonic:
    image: archivebox/sonic:latest
    container_name: ab-sonic
    user: 435:930
    restart: unless-stopped
    expose:
      - 1491
    env_file: .env
    volumes:
      - ab-sonic:/var/lib/sonic/store

  pihole:
    image: pihole/pihole:latest
    container_name: ab-pihole
    user: 435:930
    restart: unless-stopped
    ports:
      - 127.0.0.1:8090:80
    env_file: .env
    environment:
      - WEBPASSWORD=${PIHOLE_PASSWORD}
      - DNSMASQ_LISTENING=all
    volumes:
      - $HOME/homelab-data/archivebox/etc/pihole:/etc/pihole
      - $HOME/homelab-data/archivebox/etc/dnsmasq:/etc/dnsmasq.d
    dns:
      - 127.0.0.1
      - 9.9.9.9
    networks:
      dns:
        ipv4_address: 172.20.0.53

  pywb:
    image: webrecorder/pywb:latest
    container_name: ab-pywb
    user: 435:930
    restart: unless-stopped
    entrypoint: |
      /bin/sh -c '(wb-manager init default || test $$? -eq 2) \
      && wb-manager add default /archivebox/archive/*/warc/*.warc.gz;\
      wayback;'
    ports:
      - 8686:8080
    environment:
      - INIT_COLLECTION=archivebox
    volumes:
      - $HOME/homelab-data/archivebox/data:/data
      - $HOME/homelab-data/data/wayback:/webarchive

networks:
  dns:
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/24
