---
# Usage:
#     mkdir -p ~/archivebox/data && cd ~/archivebox
#     curl -fsSL 'https://docker-compose.archivebox.io' > docker-compose.yml
#     docker compose run archivebox version
#     docker compose run archivebox config --set SAVE_ARCHIVE_DOT_ORG=False
#     docker compose run archivebox add --depth=1 'https://news.ycombinator.com'
#     docker compose run -T archivebox add < bookmarks.txt
#     docker compose up -d && open 'https://localhost:8000'
#     docker compose run archivebox help
# Documentation:
#     https://github.com/ArchiveBox/ArchiveBox/wiki/Docker#docker-compose
services:
    archivebox:
        image: archivebox/archivebox:latest
        container_name: archivebox
        ports:
            - 8070:8000
        volumes:
            - $HOME/homelab-data/archivebox/data:/data
        env_file: .env
        networks:
            - dns
        dns:
            - 172.20.0.53

    archivebox_scheduler:
        image: archivebox/archivebox:latest
        container_name: ab-scheduler
        command: schedule --foreground --update --every=day
        env_file: .env
        volumes:
            - $HOME/homelab-data/archivebox/data:/data
        cpus: 1
        mem_limit: 2048m
        restart: unless-stopped

    sonic:
        image: archivebox/sonic:latest
        user: 435:930
        container_name: ab-sonic
        expose:
            - 1491
        env_file: .env
        volumes:
            - ab-sonic:/var/lib/sonic/store

    pihole:
        image: pihole/pihole:latest
        user: 435:930
        container_name: ab-pihole
        ports:
            - 127.0.0.1:8090:80
        env_file: .env
        environment:
            - WEBPASSWORD=${PIHOLE_PASSWORD}
            - DNSMASQ_LISTENING=all
        dns:
            - 127.0.0.1
            - 9.9.9.9
        networks:
            dns:
                ipv4_address: 172.20.0.53
        volumes:
            - $HOME/homelab-data/archivebox/etc/pihole:/etc/pihole
            - $HOME/homelab-data/archivebox/etc/dnsmasq:/etc/dnsmasq.d

    pywb:
        image: webrecorder/pywb:latest
        user: 435:930
        container_name: ab-pywb
        entrypoint: |
            /bin/sh -c '(wb-manager init default || test $$? -eq 2) \
            && wb-manager add default /archivebox/archive/*/warc/*.warc.gz;\
            wayback;'
        environment:
            - INIT_COLLECTION=archivebox
        ports:
            - 8686:8080
        volumes:
            - $HOME/homelab-data/archivebox/data:/data
            - $HOME/homelab-data/data/wayback:/webarchive

networks:
    dns:
        ipam:
            driver: default
            config:
                - subnet: 172.20.0.0/24
